### ISSUE TITLE
Please add an interpreter

### ISSUE THREAD

**Issue by Athas** [diku-kmc/kleenexlang#8]
A Kleenex interpreter would make it faster to develop working Kleenex programs, as I would no longer have to wait for the compiler whenever I make a change.

**Comment by ulrikrasmussen** [comment]
There is a (not thoroughly tested) interpreter interface available in d2ba6e4. The README has been updated with usage instructions.

**Comment by Athas** [comment]
It is still pretty slow, impeding my Time-to-Market:

```
$ echo 'computer' | time kexc --quiet simulate compiled/makeDanish.kex
datamat
9.14user 0.31system 0:09.46elapsed 99%CPU (0avgtext+0avgdata 555688maxresident)k
0inputs+0outputs (0major+173337minor)pagefaults 0swaps
```

What's worse, more complex rules seem not to work:

```
$ echo 'wtf' | kexc --quiet simulate compiled/makeDanish.kex
kexc: valuate: Variable not in valuation
```

The program in question is here: https://github.com/Athas/EggsML/blob/master/concieggs/compiled/makeDanish.kex

**Comment by ulrikrasmussen** [comment]
Oh my, this actually exposed several bugs! Did you ever have problems with UTF-8? Kleenex seems to output raw unicode code points, so "ø" (U+00F8) is written as a single 0xF8 instead of the UTF-8 encoding 0xC3B8.

**Comment by Athas** [comment]
Well, I have some Unicode-related problems on OpenBSD, on which GHC is a Unicode mystery all of its own, so I did not think to blame Kleenex.

**Comment by ulrikrasmussen** [comment]
Your example works now, in 07824fb. Improving performance of `kexc` is a more long-term goal, I'll have to figure out why it spends so much time on your relatively simple program.

**Comment by Athas** [comment]
Well, it runs all the oracle generation and whatnot.  Couldn't one device an interpreter for the Kleenex language that is totally divorced from the compilation pipeline?

**Comment by ulrikrasmussen** [comment]
Good point! This is now the default in e42e287

**Comment by Athas** [comment]
Now we're talking!  That is a pretty horrid user interface, though.  What about a small wrapper program, `kexci` or whatnot, that implies all that?  Or just add another subcommand, `interpret`, that behaves as `simulate --sb=false --quiet`.

**Comment by ulrikrasmussen** [comment]
Feel free to define an alias ;). The options library I'm using is a bit inflexible when it comes to implied options, which I think would be the best solution. I'll fix it some day.

**Comment by ulrikrasmussen** [comment]
Okay, I got tired of that myself pretty quickly. Now there is an `interpret` subcommand with the functionality you suggested.
